version: 2.1

jobs:
  test:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  deploy:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: yarn install
      - run: yarn global add firebase-tools
      - run: firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
